name: hrms_app
description: A new Flutter project.

publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  flutter_launcher_icons: ^0.14.3
  pie_chart: ^5.4.0
  provider: ^6.1.4
  shared_preferences: ^2.5.3

  # Localization support
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/navigation_drawer_menu.png
    - assets/images/navigation_close_button.png
    - assets/images/logo_image.png
    - assets/images/logo_image-removebg-preview.png

    - assets/icons/recruitment_menu.png
    - assets/icons/dashboard.png
    - assets/icons/dashboard_selected.png
    - assets/icons/recruitment.png
    - assets/icons/recruitment_selected.png
    - assets/icons/onboarding.png
    - assets/icons/onboarding_selected.png
    - assets/icons/employee.png
    - assets/icons/employee_selected.png
    - assets/icons/attendance.png
    - assets/icons/attendance_selected.png
    - assets/icons/leaves.png
    - assets/icons/leaves_selected.png
    - assets/icons/payroll.png
    - assets/icons/payroll_selected.png
    - assets/icons/performance.png
    - assets/icons/performance_selected.png
    - assets/icons/offboarding.png
    - assets/icons/offboarding_selected.png
    - assets/icons/assets.png
    - assets/icons/assets_selected.png
    - assets/icons/helpdesk.png
    - assets/icons/helpdesk_selected.png
    - assets/icons/configuration.png
    - assets/icons/configuration_selected.png
    - assets/icons/settings.png
    - assets/icons/settings_selected.png
    - assets/icons/notifications.png
    - assets/icons/notifications_selected.png
    - assets/icons/languages.png
    - assets/icons/languages_selected.png
    - assets/icons/companies.png
    - assets/icons/companies_selected.png
    - assets/flags/us.png
    - assets/flags/de.png
    - assets/flags/es.png
    - assets/flags/fr.png
    - assets/flags/ar.png
    - assets/flags/br.png
    - assets/flags/zh.png
    - assets/flags/in.png

  generate: true

flutter_gen:
  l10n:
    arb-dir: lib/l10n
    template-arb-file: app_en.arb
    output-dir: lib/flutter_gen/gen_l10n
    output-localization-file: app_localizations.dart
    preferred-supported-locales:
      - en
      - mr

